import { ScanResult } from "@/types";

export interface ShareData {
  title: string;
  text: string;
  url?: string;
}

/**
 * Check if Web Share API is supported
 */
export function canShare(): boolean {
  return typeof navigator !== "undefined" && "share" in navigator;
}

/**
 * Share scan result using Web Share API
 */
export async function shareScan(result: ScanResult): Promise<boolean> {
  if (!canShare()) {
    // Fallback to clipboard
    return copyToClipboard(formatScanText(result));
  }

  const shareData: ShareData = {
    title: `${result.subject}: ${result.topic}`,
    text: formatScanText(result),
    url: window.location.href,
  };

  try {
    await navigator.share(shareData);
    return true;
  } catch (error) {
    // User cancelled or error occurred
    if ((error as Error).name === "AbortError") {
      return false; // User cancelled
    }
    // Fallback to clipboard
    return copyToClipboard(shareData.text);
  }
}

/**
 * Copy text to clipboard
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (error) {
    // Fallback for older browsers
    const textArea = document.createElement("textarea");
    textArea.value = text;
    textArea.style.position = "fixed";
    textArea.style.left = "-999999px";
    document.body.appendChild(textArea);
    textArea.focus();
    textArea.select();

    try {
      document.execCommand("copy");
      document.body.removeChild(textArea);
      return true;
    } catch (err) {
      document.body.removeChild(textArea);
      return false;
    }
  }
}

/**
 * Format scan result as shareable text
 */
function formatScanText(result: ScanResult): string {
  let text = `📚 StudyLens\n\n`;
  text += `Subject: ${result.subject}\n`;
  text += `Topic: ${result.topic}\n\n`;
  text += `Problem:\n${result.extractedText}\n\n`;
  text += `Answer: ${result.explanation.simpleAnswer}\n\n`;

  if (result.explanation.stepByStep.length > 0) {
    text += `Steps:\n`;
    result.explanation.stepByStep.forEach((step) => {
      text += `${step.step}. ${step.action}\n   ${step.explanation}\n`;
    });
    text += `\n`;
  }

  text += `Concept:\n${result.explanation.concept}\n\n`;
  text += `Generated by StudyLens - AI Visual Learning Companion`;

  return text;
}
