'use client';

import { useState, useRef } from 'react';
import { FileDown, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { ScanResult } from '@/types';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

interface ExportPDFProps {
  result: ScanResult;
  imageUrl?: string;
  variant?: 'icon' | 'button';
  className?: string;
}

export function ExportPDF({
  result,
  imageUrl,
  variant = 'icon',
  className,
}: ExportPDFProps) {
  const [isExporting, setIsExporting] = useState(false);
  const contentRef = useRef<HTMLDivElement>(null);

  const generatePDF = async () => {
    setIsExporting(true);

    try {
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      const margin = 15;
      const contentWidth = pageWidth - margin * 2;
      let yPosition = margin;

      // Helper function to add footer
      const addFooter = () => {
        const footerY = pageHeight - 10;
        pdf.setFontSize(8);
        pdf.setFont('helvetica', 'normal');
        pdf.setTextColor('#9ca3af');
        pdf.text(
          'Generated by StudyLens - Your AI Learning Companion',
          margin,
          footerY
        );
        pdf.text(
          `Page ${pdf.getNumberOfPages()}`,
          pageWidth - margin - 15,
          footerY
        );
      };

      // Helper function to add new page if needed
      const checkPageBreak = (requiredHeight: number) => {
        if (yPosition + requiredHeight > pageHeight - margin - 15) {
          // 15 for footer space
          addFooter(); // Add footer before new page
          pdf.addPage();
          yPosition = margin;
          return true;
        }
        return false;
      };

      // Helper function to add text with word wrap
      const addWrappedText = (
        text: string,
        fontSize: number,
        isBold = false,
        color = '#374151'
      ) => {
        pdf.setFontSize(fontSize);
        pdf.setFont('helvetica', isBold ? 'bold' : 'normal');
        pdf.setTextColor(color);

        const lines = pdf.splitTextToSize(text, contentWidth);
        const lineHeight = fontSize * 0.5;

        lines.forEach((line: string) => {
          checkPageBreak(lineHeight);
          pdf.text(line, margin, yPosition);
          yPosition += lineHeight;
        });

        yPosition += 3;
      };

      // Helper function to add section header
      const addSectionHeader = (title: string) => {
        checkPageBreak(15);
        yPosition += 5;
        pdf.setFillColor(249, 250, 251);
        pdf.roundedRect(margin, yPosition - 5, contentWidth, 10, 2, 2, 'F');
        pdf.setFontSize(12);
        pdf.setFont('helvetica', 'bold');
        pdf.setTextColor('#1f2937');
        pdf.text(title, margin + 3, yPosition + 2);
        yPosition += 12;
      };

      // Title
      pdf.setFontSize(20);
      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor('#6366f1');
      pdf.text('StudyLens', margin, yPosition);
      yPosition += 8;

      // Date
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'normal');
      pdf.setTextColor('#6b7280');
      pdf.text(
        `Exported on ${new Date().toLocaleDateString('en-US', {
          year: 'numeric',
          month: 'long',
          day: 'numeric',
          hour: '2-digit',
          minute: '2-digit',
        })}`,
        margin,
        yPosition
      );
      yPosition += 10;

      // Divider
      pdf.setDrawColor('#e5e7eb');
      pdf.line(margin, yPosition, pageWidth - margin, yPosition);
      yPosition += 10;

      // Metadata badges
      pdf.setFontSize(10);

      // Subject badge
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor('#6b7280');
      pdf.text('Subject:', margin, yPosition);
      pdf.setFont('helvetica', 'normal');
      pdf.setTextColor('#1f2937');
      pdf.text(result.subject, margin + 20, yPosition);
      yPosition += 6;

      // Topic badge
      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor('#6b7280');
      pdf.text('Topic:', margin, yPosition);
      pdf.setFont('helvetica', 'normal');
      pdf.setTextColor('#1f2937');
      pdf.text(result.topic, margin + 20, yPosition);
      yPosition += 6;

      // Difficulty badge
      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor('#6b7280');
      pdf.text('Difficulty:', margin, yPosition);
      pdf.setFont('helvetica', 'normal');
      const diffText = result.difficulty
        ? result.difficulty.charAt(0).toUpperCase() + result.difficulty.slice(1)
        : 'Medium';
      const diffColors: Record<string, string> = {
        easy: '#166534',
        medium: '#854d0e',
        hard: '#991b1b',
      };
      pdf.setTextColor(diffColors[result.difficulty || 'medium']);
      pdf.text(diffText, margin + 23, yPosition);

      yPosition += 12;

      // Add image if available
      if (imageUrl) {
        try {
          checkPageBreak(60);
          const img = new Image();
          img.crossOrigin = 'anonymous';

          await new Promise<void>((resolve, reject) => {
            img.onload = () => resolve();
            img.onerror = () => reject();
            img.src = imageUrl;
          });

          const imgWidth = Math.min(contentWidth, 100);
          const imgHeight = (img.height / img.width) * imgWidth;
          const maxImgHeight = 50;
          const finalHeight = Math.min(imgHeight, maxImgHeight);
          const finalWidth = (finalHeight / imgHeight) * imgWidth;

          pdf.addImage(img, 'JPEG', margin, yPosition, finalWidth, finalHeight);
          yPosition += finalHeight + 10;
        } catch {
          // Skip image if it fails to load
        }
      }

      // Extracted Text
      addSectionHeader('What I See');
      addWrappedText(result.extractedText, 10, false, '#4b5563');

      // Answer
      addSectionHeader('Answer');
      pdf.setFillColor(247, 243, 245);
      const answerLines = pdf.splitTextToSize(
        result.explanation.simpleAnswer,
        contentWidth - 10
      );
      const answerHeight = answerLines.length * 6 + 8;
      checkPageBreak(answerHeight);
      pdf.roundedRect(
        margin,
        yPosition - 2,
        contentWidth,
        answerHeight,
        3,
        3,
        'F'
      );
      pdf.setFontSize(12);
      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor(31, 41, 55);
      answerLines.forEach((line: string, i: number) => {
        pdf.text(line, margin + 5, yPosition + 5 + i * 6);
      });
      yPosition += answerHeight + 8;

      // Concept
      addSectionHeader('Concept');
      addWrappedText(result.explanation.concept, 10, false, '#4b5563');

      // Why It Matters
      if (result.explanation.whyItMatters) {
        addSectionHeader('Why It Matters');
        addWrappedText(result.explanation.whyItMatters, 10, false, '#4b5563');
      }

      // Step by Step
      if (
        result.explanation.stepByStep &&
        result.explanation.stepByStep.length > 0
      ) {
        addSectionHeader('Step-by-Step Solution');

        result.explanation.stepByStep.forEach((step, index) => {
          checkPageBreak(20);

          // Step number circle
          pdf.setFillColor(99, 102, 241);
          pdf.circle(margin + 4, yPosition, 4, 'F');
          pdf.setFontSize(10);
          pdf.setFont('helvetica', 'bold');
          pdf.setTextColor('#ffffff');
          pdf.text(String(step.step), margin + 2.5, yPosition + 1.5);

          // Step action
          pdf.setTextColor('#1f2937');
          pdf.text(step.action, margin + 12, yPosition + 1);
          yPosition += 8;

          // Step explanation
          addWrappedText(step.explanation, 10, false, '#6b7280');

          // Formula if present
          if (step.formula) {
            pdf.setFillColor(243, 244, 246);
            const formulaLines = pdf.splitTextToSize(
              step.formula,
              contentWidth - 20
            );
            const formulaHeight = formulaLines.length * 5 + 6;
            checkPageBreak(formulaHeight);
            pdf.roundedRect(
              margin + 10,
              yPosition - 2,
              contentWidth - 10,
              formulaHeight,
              2,
              2,
              'F'
            );
            pdf.setFontSize(9);
            pdf.setFont('courier', 'normal');
            pdf.setTextColor('#374151');
            formulaLines.forEach((line: string, i: number) => {
              pdf.text(line, margin + 15, yPosition + 3 + i * 5);
            });
            yPosition += formulaHeight + 5;
          }

          yPosition += 3;
        });
      }

      // Tips
      if (result.explanation.tips && result.explanation.tips.length > 0) {
        addSectionHeader('Tips');

        result.explanation.tips.forEach((tip) => {
          checkPageBreak(10);
          pdf.setFontSize(10);
          pdf.setTextColor('#6366f1');
          pdf.text('•', margin + 2, yPosition);
          pdf.setTextColor('#4b5563');
          const tipLines = pdf.splitTextToSize(tip, contentWidth - 10);
          tipLines.forEach((line: string, i: number) => {
            pdf.text(line, margin + 8, yPosition + i * 5);
          });
          yPosition += tipLines.length * 5 + 3;
        });
      }

      // Practice Questions
      if (
        result.explanation.practiceQuestions &&
        result.explanation.practiceQuestions.length > 0
      ) {
        addSectionHeader('Practice Problems');

        result.explanation.practiceQuestions.forEach((question, index) => {
          checkPageBreak(15);
          pdf.setFillColor(249, 250, 251);
          const questionLines = pdf.splitTextToSize(
            `${index + 1}. ${question}`,
            contentWidth - 10
          );
          const questionHeight = questionLines.length * 5 + 6;
          pdf.roundedRect(
            margin,
            yPosition - 2,
            contentWidth,
            questionHeight,
            2,
            2,
            'F'
          );
          pdf.setFontSize(10);
          pdf.setFont('helvetica', 'normal');
          pdf.setTextColor('#374151');
          questionLines.forEach((line: string, i: number) => {
            pdf.text(line, margin + 5, yPosition + 3 + i * 5);
          });
          yPosition += questionHeight + 4;
        });
      }

      // Footer on last page
      addFooter();

      // Save the PDF
      const fileName = `StudyLens-${result.topic.replace(/\s+/g, '-')}-${
        new Date().toISOString().split('T')[0]
      }.pdf`;
      pdf.save(fileName);
    } catch (error) {
      console.error('Failed to generate PDF:', error);
    } finally {
      setIsExporting(false);
    }
  };

  if (variant === 'icon') {
    return (
      <Button
        variant="ghost"
        size="icon"
        onClick={generatePDF}
        disabled={isExporting}
        className={className}
        title="Export as PDF"
      >
        {isExporting ? (
          <Loader2 className="h-5 w-5 animate-spin" />
        ) : (
          <FileDown className="h-5 w-5" />
        )}
      </Button>
    );
  }

  return (
    <Button
      variant="outline"
      onClick={generatePDF}
      disabled={isExporting}
      className={className}
    >
      {isExporting ? (
        <Loader2 className="h-4 w-4 animate-spin mr-2" />
      ) : (
        <FileDown className="h-4 w-4 mr-2" />
      )}
      Export PDF
    </Button>
  );
}
